%complex name root parent
%multiple parents
%no parent
%root parent
dirParent(parent("/"),child("/complex_file+name.txt.whatever")).
dirParent(parent("/"),child("/rootParent")).
dirParent(parent("/a"),child("/a/one")).
dirParent(parent("/a"),child("/a/two")).
dirParent(parent("/a/one"),child("/a/one/alpha")).
dirParent(parent("/a/one"),child("/a/one/beta")).
dirParent(parent("/b"),child("/b/one")).
dirParent(parent("/b/one"),child("/b/one/alpha")).
dirParent(parent("rootDirectoryHasNoParent"),child("/")).
filePermissionBits(permissionBits(0),filePath("/")).
filePermissionBits(permissionBits(0),filePath("/a/one")).
filePermissionBits(permissionBits(0),filePath("/a/one/alpha")).
filePermissionBits(permissionBits(0),filePath("/a/one/beta")).
filePermissionBits(permissionBits(0),filePath("/a/two")).
filePermissionBits(permissionBits(0),filePath("/b/one")).
filePermissionBits(permissionBits(0),filePath("/b/one/alpha")).
filePermissionBits(permissionBits(0),filePath("/complex_file+name.txt.whatever")).
filePermissionBits(permissionBits(0),filePath("/rootParent")).
groupexecute(0,"/").
groupexecute(0,"/a/one").
groupexecute(0,"/a/one/alpha").
groupexecute(0,"/a/one/beta").
groupexecute(0,"/a/two").
groupexecute(0,"/b/one").
groupexecute(0,"/b/one/alpha").
groupexecute(0,"/complex_file+name.txt.whatever").
groupexecute(0,"/rootParent").
groupread(0,"/").
groupread(0,"/a/one").
groupread(0,"/a/one/alpha").
groupread(0,"/a/one/beta").
groupread(0,"/a/two").
groupread(0,"/b/one").
groupread(0,"/b/one/alpha").
groupread(0,"/complex_file+name.txt.whatever").
groupread(0,"/rootParent").
groupspecial(0,"/").
groupspecial(0,"/a/one").
groupspecial(0,"/a/one/alpha").
groupspecial(0,"/a/one/beta").
groupspecial(0,"/a/two").
groupspecial(0,"/b/one").
groupspecial(0,"/b/one/alpha").
groupspecial(0,"/complex_file+name.txt.whatever").
groupspecial(0,"/rootParent").
groupwrite(0,"/").
groupwrite(0,"/a/one").
groupwrite(0,"/a/one/alpha").
groupwrite(0,"/a/one/beta").
groupwrite(0,"/a/two").
groupwrite(0,"/b/one").
groupwrite(0,"/b/one/alpha").
groupwrite(0,"/complex_file+name.txt.whatever").
groupwrite(0,"/rootParent").
otherexecute(0,"/").
otherexecute(0,"/a/one").
otherexecute(0,"/a/one/alpha").
otherexecute(0,"/a/one/beta").
otherexecute(0,"/a/two").
otherexecute(0,"/b/one").
otherexecute(0,"/b/one/alpha").
otherexecute(0,"/complex_file+name.txt.whatever").
otherexecute(0,"/rootParent").
otherread(0,"/").
otherread(0,"/a/one").
otherread(0,"/a/one/alpha").
otherread(0,"/a/one/beta").
otherread(0,"/a/two").
otherread(0,"/b/one").
otherread(0,"/b/one/alpha").
otherread(0,"/complex_file+name.txt.whatever").
otherread(0,"/rootParent").
otherspecial(0,"/").
otherspecial(0,"/a/one").
otherspecial(0,"/a/one/alpha").
otherspecial(0,"/a/one/beta").
otherspecial(0,"/a/two").
otherspecial(0,"/b/one").
otherspecial(0,"/b/one/alpha").
otherspecial(0,"/complex_file+name.txt.whatever").
otherspecial(0,"/rootParent").
otherwrite(0,"/").
otherwrite(0,"/a/one").
otherwrite(0,"/a/one/alpha").
otherwrite(0,"/a/one/beta").
otherwrite(0,"/a/two").
otherwrite(0,"/b/one").
otherwrite(0,"/b/one/alpha").
otherwrite(0,"/complex_file+name.txt.whatever").
otherwrite(0,"/rootParent").
userexecute(0,"/").
userexecute(0,"/a/one").
userexecute(0,"/a/one/alpha").
userexecute(0,"/a/one/beta").
userexecute(0,"/a/two").
userexecute(0,"/b/one").
userexecute(0,"/b/one/alpha").
userexecute(0,"/complex_file+name.txt.whatever").
userexecute(0,"/rootParent").
userread(0,"/").
userread(0,"/a/one").
userread(0,"/a/one/alpha").
userread(0,"/a/one/beta").
userread(0,"/a/two").
userread(0,"/b/one").
userread(0,"/b/one/alpha").
userread(0,"/complex_file+name.txt.whatever").
userread(0,"/rootParent").
userspecial(0,"/").
userspecial(0,"/a/one").
userspecial(0,"/a/one/alpha").
userspecial(0,"/a/one/beta").
userspecial(0,"/a/two").
userspecial(0,"/b/one").
userspecial(0,"/b/one/alpha").
userspecial(0,"/complex_file+name.txt.whatever").
userspecial(0,"/rootParent").
userwrite(0,"/").
userwrite(0,"/a/one").
userwrite(0,"/a/one/alpha").
userwrite(0,"/a/one/beta").
userwrite(0,"/a/two").
userwrite(0,"/b/one").
userwrite(0,"/b/one/alpha").
userwrite(0,"/complex_file+name.txt.whatever").
userwrite(0,"/rootParent").
