group(groupName("nobody"),passwordHash("*"),id("-2"),members([""])).
group(groupName("nogroup"),passwordHash("*"),id("-1"),members([""])).
group(groupName("wheel"),passwordHash("*"),id("0"),members(["root"])).
group(groupName("daemon"),passwordHash("*"),id("1"),members(["root"])).
group(groupName("kmem"),passwordHash("*"),id("2"),members(["root"])).
group(groupName("sys"),passwordHash("*"),id("3"),members(["root"])).
group(groupName("tty"),passwordHash("*"),id("4"),members(["root"])).
group(groupName("operator"),passwordHash("*"),id("5"),members(["root"])).
group(groupName("mail"),passwordHash("*"),id("6"),members([""])).
group(groupName("bin"),passwordHash("*"),id("7"),members([""])).
group(groupName("procview"),passwordHash("*"),id("8"),members(["root"])).
group(groupName("procmod"),passwordHash("*"),id("9"),members(["root"])).
group(groupName("owner"),passwordHash("*"),id("10"),members([""])).
group(groupName("everyone"),passwordHash("*"),id("12"),members([""])).
group(groupName("group"),passwordHash("*"),id("16"),members([""])).
group(groupName("staff"),passwordHash("*"),id("20"),members(["root"])).
group(groupName("_networkd"),passwordHash("*"),id("24"),members([""])).
group(groupName("_wireless"),passwordHash("*"),id("25"),members([""])).
group(groupName("_lp"),passwordHash("*"),id("26"),members([""])).
group(groupName("_postfix"),passwordHash("*"),id("27"),members([""])).
group(groupName("_postdrop"),passwordHash("*"),id("28"),members([""])).
group(groupName("certusers"),passwordHash("*"),id("29"),members(["root","_jabber","_postfix","_cyrus","_calendar"])).
group(groupName("_keytabusers"),passwordHash("*"),id("30"),members(["_calendar","_jabber","_postfix"])).
group(groupName("_neagent"),passwordHash("*"),id("34"),members([""])).
group(groupName("utmp"),passwordHash("*"),id("45"),members([""])).
group(groupName("authedusers"),passwordHash("*"),id("50"),members([""])).
group(groupName("interactusers"),passwordHash("*"),id("51"),members([""])).
group(groupName("netusers"),passwordHash("*"),id("52"),members([""])).
group(groupName("consoleusers"),passwordHash("*"),id("53"),members([""])).
group(groupName("_mcxalr"),passwordHash("*"),id("54"),members([""])).
group(groupName("_serialnumberd"),passwordHash("*"),id("58"),members([""])).
group(groupName("_devdocs"),passwordHash("*"),id("59"),members([""])).
group(groupName("_sandbox"),passwordHash("*"),id("60"),members([""])).
group(groupName("localaccounts"),passwordHash("*"),id("61"),members([""])).
group(groupName("netaccounts"),passwordHash("*"),id("62"),members([""])).
group(groupName("_securityd"),passwordHash("*"),id("64"),members(["_securityd"])).
group(groupName("_mdnsresponder"),passwordHash("*"),id("65"),members([""])).
group(groupName("_uucp"),passwordHash("*"),id("66"),members([""])).
group(groupName("_ard"),passwordHash("*"),id("67"),members([""])).
group(groupName("dialer"),passwordHash("*"),id("68"),members([""])).
group(groupName("network"),passwordHash("*"),id("69"),members([""])).
group(groupName("_www"),passwordHash("*"),id("70"),members([""])).
group(groupName("_cvs"),passwordHash("*"),id("72"),members([""])).
group(groupName("_svn"),passwordHash("*"),id("73"),members([""])).
group(groupName("_mysql"),passwordHash("*"),id("74"),members([""])).
group(groupName("_sshd"),passwordHash("*"),id("75"),members([""])).
group(groupName("_qtss"),passwordHash("*"),id("76"),members([""])).
group(groupName("_mailman"),passwordHash("*"),id("78"),members([""])).
group(groupName("_appserverusr"),passwordHash("*"),id("79"),members([""])).
group(groupName("admin"),passwordHash("*"),id("80"),members(["root"])).
group(groupName("_appserveradm"),passwordHash("*"),id("81"),members([""])).
group(groupName("_clamav"),passwordHash("*"),id("82"),members([""])).
group(groupName("_amavisd"),passwordHash("*"),id("83"),members([""])).
group(groupName("_jabber"),passwordHash("*"),id("84"),members([""])).
group(groupName("_appowner"),passwordHash("*"),id("87"),members([""])).
group(groupName("_windowserver"),passwordHash("*"),id("88"),members([""])).
group(groupName("_spotlight"),passwordHash("*"),id("89"),members([""])).
group(groupName("accessibility"),passwordHash("*"),id("90"),members([""])).
group(groupName("_tokend"),passwordHash("*"),id("91"),members([""])).
group(groupName("_securityagent"),passwordHash("*"),id("92"),members([""])).
group(groupName("_calendar"),passwordHash("*"),id("93"),members(["_teamsserver"])).
group(groupName("_teamsserver"),passwordHash("*"),id("94"),members([""])).
group(groupName("_update_sharing"),passwordHash("*"),id("95"),members([""])).
group(groupName("_installer"),passwordHash("*"),id("96"),members([""])).
group(groupName("_atsserver"),passwordHash("*"),id("97"),members([""])).
group(groupName("_lpadmin"),passwordHash("*"),id("98"),members([""])).
group(groupName("_unknown"),passwordHash("*"),id("99"),members([""])).
group(groupName("_distnote"),passwordHash("*"),id("241"),members([""])).
group(groupName("mobile"),passwordHash("*"),id("501"),members(["mobile"])).
