
  ["../prolog/groups"],
  ["../prolog/unixAllowRules"],
  ["../prolog/unixPermissionsForTests"].
  ["../prolog/users"],
%all permissions
%no permissions
%one and two digits
%rainbow pattern
:-
dirParent(parent("/"),child("/all")).
dirParent(parent("/"),child("/none")).
dirParent(parent("/"),child("/onedigit")).
dirParent(parent("/"),child("/rainbow0123")).
dirParent(parent("/"),child("/rainbow3210")).
dirParent(parent("/"),child("/rainbow4567")).
dirParent(parent("/"),child("/rainbow7654")).
dirParent(parent("/"),child("/twodigit")).
filePermissionBits(permissionBits(0),filePath("/none")).
filePermissionBits(permissionBits(0123),filePath("/rainbow0123")).
filePermissionBits(permissionBits(3210),filePath("/rainbow3210")).
filePermissionBits(permissionBits(35),filePath("/twodigit")).
filePermissionBits(permissionBits(4),filePath("/onedigit")).
filePermissionBits(permissionBits(4567),filePath("/rainbow4567")).
filePermissionBits(permissionBits(7654),filePath("/rainbow7654")).
filePermissionBits(permissionBits(7777),filePath("/all")).
groupexecute(0,"/none").
groupexecute(0,"/onedigit").
groupexecute(0,"/rainbow0123").
groupexecute(0,"/rainbow4567").
groupexecute(1,"/all").
groupexecute(1,"/rainbow3210").
groupexecute(1,"/rainbow7654").
groupexecute(1,"/twodigit").
groupread(0,"/none").
groupread(0,"/onedigit").
groupread(0,"/rainbow0123").
groupread(0,"/rainbow3210").
groupread(0,"/twodigit").
groupread(1,"/all").
groupread(1,"/rainbow4567").
groupread(1,"/rainbow7654").
groupspecial(0,"/none").
groupspecial(0,"/onedigit").
groupspecial(0,"/rainbow0123").
groupspecial(0,"/rainbow4567").
groupspecial(0,"/twodigit").
groupspecial(1,"/all").
groupspecial(1,"/rainbow3210").
groupspecial(1,"/rainbow7654").
groupwrite(0,"/none").
groupwrite(0,"/onedigit").
groupwrite(0,"/rainbow3210").
groupwrite(0,"/rainbow7654").
groupwrite(1,"/all").
groupwrite(1,"/rainbow0123").
groupwrite(1,"/rainbow4567").
groupwrite(1,"/twodigit").
otherexecute(0,"/none").
otherexecute(0,"/onedigit").
otherexecute(0,"/rainbow3210").
otherexecute(0,"/rainbow7654").
otherexecute(1,"/all").
otherexecute(1,"/rainbow0123").
otherexecute(1,"/rainbow4567").
otherexecute(1,"/twodigit").
otherread(0,"/none").
otherread(0,"/rainbow0123").
otherread(0,"/rainbow3210").
otherread(1,"/all").
otherread(1,"/onedigit").
otherread(1,"/rainbow4567").
otherread(1,"/rainbow7654").
otherread(1,"/twodigit").
otherspecial(0,"/none").
otherspecial(0,"/onedigit").
otherspecial(0,"/rainbow0123").
otherspecial(0,"/rainbow4567").
otherspecial(0,"/twodigit").
otherspecial(1,"/all").
otherspecial(1,"/rainbow3210").
otherspecial(1,"/rainbow7654").
otherwrite(0,"/none").
otherwrite(0,"/onedigit").
otherwrite(0,"/rainbow3210").
otherwrite(0,"/rainbow7654").
otherwrite(0,"/twodigit").
otherwrite(1,"/all").
otherwrite(1,"/rainbow0123").
otherwrite(1,"/rainbow4567").
userexecute(0,"/none").
userexecute(0,"/onedigit").
userexecute(0,"/rainbow3210").
userexecute(0,"/rainbow7654").
userexecute(0,"/twodigit").
userexecute(1,"/all").
userexecute(1,"/rainbow0123").
userexecute(1,"/rainbow4567").
userread(0,"/none").
userread(0,"/onedigit").
userread(0,"/rainbow0123").
userread(0,"/rainbow3210").
userread(0,"/twodigit").
userread(1,"/all").
userread(1,"/rainbow4567").
userread(1,"/rainbow7654").
userspecial(0,"/none").
userspecial(0,"/onedigit").
userspecial(0,"/rainbow0123").
userspecial(0,"/rainbow3210").
userspecial(0,"/twodigit").
userspecial(1,"/all").
userspecial(1,"/rainbow4567").
userspecial(1,"/rainbow7654").
userwrite(0,"/none").
userwrite(0,"/onedigit").
userwrite(0,"/rainbow0123").
userwrite(0,"/rainbow4567").
userwrite(0,"/twodigit").
userwrite(1,"/all").
userwrite(1,"/rainbow3210").
userwrite(1,"/rainbow7654").
