processOwnership(uid("0"),gid("0"),comm("(bash)")).
processOwnership(uid("0"),gid("0"),comm("-sh")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/CoreServices/AppleIDAuthAgent")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/CoreServices/ReportCrash")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/CoreServices/powerd.bundle/powerd")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/Frameworks/LocalAuthentication.framework/Support/coreauthd")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/Frameworks/Security.framework/CloudKeychainProxy.bundle/CloudKeychainProxy")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/Frameworks/Security.framework/IDSKeychainSyncingProxy.bundle/IDSKeychainSyncingProxy")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/PrivateFrameworks/CoreSymbolication.framework/coresymbolicationd")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/PrivateFrameworks/GenerationalStorage.framework/revisiond")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/PrivateFrameworks/MobileBackup.framework/backupd")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/PrivateFrameworks/MobileContainerManager.framework/Support/containermanagerd")).
processOwnership(uid("0"),gid("0"),comm("/System/Library/PrivateFrameworks/MobileInstallation.framework/XPCServices/com.apple.MobileInstallationHelperService.xpc/com.apple.MobileInstallationHelperService")).
processOwnership(uid("0"),gid("0"),comm("/sbin/launchd")).
processOwnership(uid("0"),gid("0"),comm("/temporaryDirectoryForiOracleExtraction/filemon")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/BackupAgent2")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/OTATaskingAgent")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/UserEventAgent")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/assertiond")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/configd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/diagnosticd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/fseventsd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/hangtracerd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/keybagd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/locationd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/lockdownd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/logd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/microstackshot")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/misd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/mmaintenanced")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/mobileassetd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/nehelper")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/nesessionmanager")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/online-auth-agent")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/pfd")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/pipelined")).
processOwnership(uid("0"),gid("0"),comm("/usr/libexec/pkd")).
processOwnership(uid("0"),gid("0"),comm("/usr/local/bin/dropbear")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/cfprefsd")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/filecoordinationd")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/mDNSResponderHelper")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/notifyd")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/spindump")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/syslogd")).
processOwnership(uid("0"),gid("0"),comm("/usr/sbin/wifid")).
processOwnership(uid("0"),gid("0"),comm("aslmanager")).
processOwnership(uid("0"),gid("0"),comm("bash")).
processOwnership(uid("0"),gid("0"),comm("ps")).
processOwnership(uid("24"),gid("24"),comm("/usr/libexec/symptomsd")).
processOwnership(uid("25"),gid("25"),comm("/System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter")).
processOwnership(uid("25"),gid("25"),comm("/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Support/awdd")).
processOwnership(uid("33"),gid("33"),comm("/usr/libexec/installd")).
processOwnership(uid("64"),gid("64"),comm("/usr/libexec/OTAPKIAssetTool")).
processOwnership(uid("64"),gid("64"),comm("/usr/libexec/securityd")).
processOwnership(uid("65"),gid("65"),comm("/usr/sbin/mDNSResponder")).
processOwnership(uid("241"),gid("241"),comm("/usr/sbin/distnoted")).
processOwnership(uid("258"),gid("258"),comm("/usr/libexec/captiveagent")).
processOwnership(uid("501"),gid("501"),comm("/Applications/AdSheet.app/AdSheet")).
processOwnership(uid("501"),gid("501"),comm("/Applications/AppStore.app/AppStore")).
processOwnership(uid("501"),gid("501"),comm("/Applications/Contacts.app/PlugIns/ContactsCoreSpotlightExtension.appex/ContactsCoreSpotlightExtension")).
processOwnership(uid("501"),gid("501"),comm("/Applications/Cydia.app/Cydia")).
processOwnership(uid("501"),gid("501"),comm("/Applications/FaceTime.app/FaceTime")).
processOwnership(uid("501"),gid("501"),comm("/Applications/Home.app/Home")).
processOwnership(uid("501"),gid("501"),comm("/Applications/InCallService.app/InCallService")).
processOwnership(uid("501"),gid("501"),comm("/Applications/MobileMail.app/MobileMail")).
processOwnership(uid("501"),gid("501"),comm("/Applications/MobileSlideShow.app/MobileSlideShow")).
processOwnership(uid("501"),gid("501"),comm("/Applications/News.app/News")).
processOwnership(uid("501"),gid("501"),comm("/Applications/News.app/PlugIns/NewsToday.appex/NewsToday")).
processOwnership(uid("501"),gid("501"),comm("/Applications/Preferences.app/Preferences")).
processOwnership(uid("501"),gid("501"),comm("/Applications/ServerDocuments.app/PlugIns/ServerFileProvider.appex/ServerFileProvider")).
processOwnership(uid("501"),gid("501"),comm("/Applications/Weather.app/PlugIns/WeatherAppTodayWidget.appex/WeatherAppTodayWidget")).
processOwnership(uid("501"),gid("501"),comm("/Developer/usr/libexec/neagent")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/CoreServices/CacheDeleteAppContainerCaches")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/CoreServices/CacheDeleteDaily")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/CoreServices/CacheDeleteITunesStore")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/CoreServices/EscrowSecurityAlert.app/EscrowSecurityAlert")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/CoreServices/SpringBoard.app/SpringBoard")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/Accounts.framework/accountsd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/AssetsLibrary.framework/Support/assetsd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/CallKit.framework/XPCServices/com.apple.CallKit.CallDirectory.xpc/com.apple.CallKit.CallDirectory")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/HealthKit.framework/healthd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/MediaAccessibility.framework/XPCServices/com.apple.accessibility.mediaaccessibilityd.xpc/com.apple.accessibility.mediaaccessibilityd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/Metal.framework/XPCServices/MTLCompilerService.xpc/MTLCompilerService")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/Frameworks/VideoSubscriberAccount.framework/XPCServices/com.apple.VideoSubscriberAccount.DeveloperService.xpc/com.apple.VideoSubscriberAccount.DeveloperService")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AGXCompilerConnection.framework/XPCServices/AGXCompilerService.xpc/AGXCompilerService")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AXHearingSupport.framework/XPCServices/heard.xpc/heard")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AccessibilityUI.framework/XPCServices/com.apple.accessibility.AccessibilityUIServer.xpc/com.apple.accessibility.AccessibilityUIServer")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AggregateDictionary.framework/Support/aggregated")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AppStoreDaemon.framework/appstored.bundle/appstored")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/ApplePushService.framework/apsd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AskPermission.framework/askpermissiond")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AssetCacheServices.framework/XPCServices/AssetCacheLocatorService.xpc/AssetCacheLocatorService")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AssistantServices.framework/XPCServices/com.apple.siri.ClientFlow.ClientScripter.xpc/com.apple.siri.ClientFlow.ClientScripter")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AssistantServices.framework/assistant_service")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AssistantServices.framework/assistantd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/AuthKit.framework/akd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CacheDelete.framework/deleted")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CalendarDaemon.framework/Support/calaccessd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CallHistory.framework/Support/CallHistorySyncHelper")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CloudDocsDaemon.framework/XPCServices/ContainerMetadataExtractor.xpc/ContainerMetadataExtractor")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CloudDocsDaemon.framework/bird")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CloudKitDaemon.framework/Support/cloudd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CloudPhotoServices.framework/Support/CloudPhotoDerivativeGenerator")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CloudServices.framework/XPCServices/com.apple.sbd.xpc/com.apple.sbd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CommunicationsFilter.framework/CMFSyncAgent.app/CMFSyncAgent")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CoreFollowUp.framework/followupd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CoreParsec.framework/parsecd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CoreRecents.framework/recentsd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/CoreSuggestions.framework/suggestd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/DataAccess.framework/Support/dataaccessd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/FamilyCircle.framework/familycircled")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/FamilyNotification.framework/familynotificationd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/FileProvider.framework/Support/fileproviderd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/GeoServices.framework/geod")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/HomeKitDaemon.framework/Support/homed")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/HomeSharing.framework/Support/itunescloudd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/IAP.framework/Support/iaptransportd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/identityservicesd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/IMCore.framework/imagent.app/imagent")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/IMDPersistence.framework/XPCServices/IMDPersistenceAgent.xpc/IMDPersistenceAgent")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/ManagedConfiguration.framework/Support/profiled")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/MapsSupport.framework/mapspushd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/MediaRemote.framework/Support/mediaremoted")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/MediaStream.framework/Support/mstreamd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/MusicLibrary.framework/Support/medialibraryd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/PassKitCore.framework/passd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/Pasteboard.framework/Support/pasted")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/PhotoAnalysis.framework/Support/photoanalysisd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Helpers/ProtectedCloudKeySyncing")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/QuickLookThumbnailing.framework/Support/com.apple.quicklook.ThumbnailsAgent")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/Search.framework/searchd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/SoftwareUpdateServices.framework/Support/softwareupdateservicesd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/StoreBookkeeperClient.framework/Support/storebookkeeperd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/StreamingZip.framework/XPCServices/com.apple.StreamingUnzipService.xpc/com.apple.StreamingUnzipService")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/TCC.framework/tccd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/TelephonyUtilities.framework/callservicesd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/TouchRemote.framework/Support/touchsetupd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/UIFoundation.framework/XPCServices/com.apple.uifoundation-bundle-helper.xpc/com.apple.uifoundation-bundle-helper")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/UpNextWidget.framework/PlugIns/UpNext.appex/UpNext")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/UserActivity.framework/Agents/useractivityd")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/VoiceServices.framework/Support/voiced")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/iCloudNotification.framework/ind")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/PrivateFrameworks/iTunesStore.framework/Support/itunesstored")).
processOwnership(uid("501"),gid("501"),comm("/System/Library/TextInput/kbd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/DuetHeuristic-BM")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/MobileGestaltHelper")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/adid")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/afcd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/atc")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/backboardd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/coreduetd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/duetexpertd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/findmydeviced")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/fmfd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/fmflocatord")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/limitadtrackingd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/lockbot")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/lsd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/misagent")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/mobile_assertion_agent")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/mobile_installation_proxy")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/mobileactivationd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/notification_proxy")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/nsurlsessiond")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/nsurlstoraged")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/ptpd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/replayd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/routined")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/sharingd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/splashboardd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/swcd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/symptomsd-diag")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/timed")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/tipsd")).
processOwnership(uid("501"),gid("501"),comm("/usr/libexec/webbookmarksd")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/BTLEServer")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/BTServer")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/BlueTool")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/WirelessRadioManagerd")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/absd")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/fairplayd.O2")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/mediaserverd")).
processOwnership(uid("501"),gid("501"),comm("/usr/sbin/wirelessproxd")).
processOwnership(uid("501"),gid("501"),comm("/var/containers/Bundle/Application/25577A9B-A433-4758-A163-EEE650365119/Snaps")).
processOwnership(uid("501"),gid("501"),comm("OTACrashCopier")).
