dirParent(parent("/"),child("/all")).
dirParent(parent("/"),child("/noexec")).
dirParent(parent("/"),child("/none")).
dirParent(parent("/"),child("/noread")).
dirParent(parent("/"),child("/nowrite")).
dirParent(parent("/all"),child("/all/noexec")).
dirParent(parent("/all"),child("/all/noread")).
dirParent(parent("/all"),child("/all/nowrite")).
dirParent(parent("/all/noexec"),child("/all/noexec/noread")).
dirParent(parent("/all/noread"),child("/all/noread/nowrite")).
dirParent(parent("/all/nowrite"),child("/all/nowrite/noexec")).
dirParent(parent("/none"),child("/none/noexec")).
dirParent(parent("/none"),child("/none/noread")).
dirParent(parent("/none"),child("/none/nowrite")).
dirParent(parent("/none/noexec"),child("/none/noexec/noread")).
dirParent(parent("/none/noread"),child("/none/noread/nowrite")).
dirParent(parent("/none/nowrite"),child("/none/nowrite/noexec")).
dirParent(parent("rootDirectoryHasNoParent"),child("/")).
