groupexecute(0,"/").
groupexecute(0,"/all").
groupexecute(0,"/all/noexec").
groupexecute(0,"/all/noexec/noread").
groupexecute(0,"/all/noread").
groupexecute(0,"/all/noread/nowrite").
groupexecute(0,"/all/nowrite").
groupexecute(0,"/all/nowrite/noexec").
groupexecute(0,"/noexec").
groupexecute(0,"/none").
groupexecute(0,"/none/noexec").
groupexecute(0,"/none/noexec/noread").
groupexecute(0,"/none/noread").
groupexecute(0,"/none/noread/nowrite").
groupexecute(0,"/none/nowrite").
groupexecute(0,"/none/nowrite/noexec").
groupexecute(0,"/noread").
groupexecute(0,"/nowrite").
groupread(0,"/").
groupread(0,"/all").
groupread(0,"/all/noexec").
groupread(0,"/all/noexec/noread").
groupread(0,"/all/noread").
groupread(0,"/all/noread/nowrite").
groupread(0,"/all/nowrite").
groupread(0,"/all/nowrite/noexec").
groupread(0,"/noexec").
groupread(0,"/none").
groupread(0,"/none/noexec").
groupread(0,"/none/noexec/noread").
groupread(0,"/none/noread").
groupread(0,"/none/noread/nowrite").
groupread(0,"/none/nowrite").
groupread(0,"/none/nowrite/noexec").
groupread(0,"/noread").
groupread(0,"/nowrite").
groupspecial(0,"/").
groupspecial(0,"/all").
groupspecial(0,"/all/noexec").
groupspecial(0,"/all/noexec/noread").
groupspecial(0,"/all/noread").
groupspecial(0,"/all/noread/nowrite").
groupspecial(0,"/all/nowrite").
groupspecial(0,"/all/nowrite/noexec").
groupspecial(0,"/noexec").
groupspecial(0,"/none").
groupspecial(0,"/none/noexec").
groupspecial(0,"/none/noexec/noread").
groupspecial(0,"/none/noread").
groupspecial(0,"/none/noread/nowrite").
groupspecial(0,"/none/nowrite").
groupspecial(0,"/none/nowrite/noexec").
groupspecial(0,"/noread").
groupspecial(0,"/nowrite").
groupwrite(0,"/").
groupwrite(0,"/all").
groupwrite(0,"/all/noexec").
groupwrite(0,"/all/noexec/noread").
groupwrite(0,"/all/noread").
groupwrite(0,"/all/noread/nowrite").
groupwrite(0,"/all/nowrite").
groupwrite(0,"/all/nowrite/noexec").
groupwrite(0,"/noexec").
groupwrite(0,"/none").
groupwrite(0,"/none/noexec").
groupwrite(0,"/none/noexec/noread").
groupwrite(0,"/none/noread").
groupwrite(0,"/none/noread/nowrite").
groupwrite(0,"/none/nowrite").
groupwrite(0,"/none/nowrite/noexec").
groupwrite(0,"/noread").
groupwrite(0,"/nowrite").
otherexecute(0,"/").
otherexecute(0,"/all").
otherexecute(0,"/all/noexec").
otherexecute(0,"/all/noexec/noread").
otherexecute(0,"/all/noread").
otherexecute(0,"/all/noread/nowrite").
otherexecute(0,"/all/nowrite").
otherexecute(0,"/all/nowrite/noexec").
otherexecute(0,"/noexec").
otherexecute(0,"/none").
otherexecute(0,"/none/noexec").
otherexecute(0,"/none/noexec/noread").
otherexecute(0,"/none/noread").
otherexecute(0,"/none/noread/nowrite").
otherexecute(0,"/none/nowrite").
otherexecute(0,"/none/nowrite/noexec").
otherexecute(0,"/noread").
otherexecute(0,"/nowrite").
otherread(0,"/").
otherread(0,"/all").
otherread(0,"/all/noexec").
otherread(0,"/all/noexec/noread").
otherread(0,"/all/noread").
otherread(0,"/all/noread/nowrite").
otherread(0,"/all/nowrite").
otherread(0,"/all/nowrite/noexec").
otherread(0,"/noexec").
otherread(0,"/none").
otherread(0,"/none/noexec").
otherread(0,"/none/noexec/noread").
otherread(0,"/none/noread").
otherread(0,"/none/noread/nowrite").
otherread(0,"/none/nowrite").
otherread(0,"/none/nowrite/noexec").
otherread(0,"/noread").
otherread(0,"/nowrite").
otherspecial(0,"/").
otherspecial(0,"/all").
otherspecial(0,"/all/noexec").
otherspecial(0,"/all/noexec/noread").
otherspecial(0,"/all/noread").
otherspecial(0,"/all/noread/nowrite").
otherspecial(0,"/all/nowrite").
otherspecial(0,"/all/nowrite/noexec").
otherspecial(0,"/noexec").
otherspecial(0,"/none").
otherspecial(0,"/none/noexec").
otherspecial(0,"/none/noexec/noread").
otherspecial(0,"/none/noread").
otherspecial(0,"/none/noread/nowrite").
otherspecial(0,"/none/nowrite").
otherspecial(0,"/none/nowrite/noexec").
otherspecial(0,"/noread").
otherspecial(0,"/nowrite").
otherwrite(0,"/").
otherwrite(0,"/all").
otherwrite(0,"/all/noexec").
otherwrite(0,"/all/noexec/noread").
otherwrite(0,"/all/noread").
otherwrite(0,"/all/noread/nowrite").
otherwrite(0,"/all/nowrite").
otherwrite(0,"/all/nowrite/noexec").
otherwrite(0,"/noexec").
otherwrite(0,"/none").
otherwrite(0,"/none/noexec").
otherwrite(0,"/none/noexec/noread").
otherwrite(0,"/none/noread").
otherwrite(0,"/none/noread/nowrite").
otherwrite(0,"/none/nowrite").
otherwrite(0,"/none/nowrite/noexec").
otherwrite(0,"/noread").
otherwrite(0,"/nowrite").
userexecute(0,"/all/noexec").
userexecute(0,"/all/nowrite/noexec").
userexecute(0,"/noexec").
userexecute(0,"/none").
userexecute(0,"/none/noexec").
userexecute(0,"/none/nowrite/noexec").
userexecute(1,"/").
userexecute(1,"/all").
userexecute(1,"/all/noexec/noread").
userexecute(1,"/all/noread").
userexecute(1,"/all/noread/nowrite").
userexecute(1,"/all/nowrite").
userexecute(1,"/none/noexec/noread").
userexecute(1,"/none/noread").
userexecute(1,"/none/noread/nowrite").
userexecute(1,"/none/nowrite").
userexecute(1,"/noread").
userexecute(1,"/nowrite").
userread(0,"/").
userread(0,"/all/noexec/noread").
userread(0,"/all/noread").
userread(0,"/none").
userread(0,"/none/noexec/noread").
userread(0,"/none/noread").
userread(0,"/noread").
userread(1,"/all").
userread(1,"/all/noexec").
userread(1,"/all/noread/nowrite").
userread(1,"/all/nowrite").
userread(1,"/all/nowrite/noexec").
userread(1,"/noexec").
userread(1,"/none/noexec").
userread(1,"/none/noread/nowrite").
userread(1,"/none/nowrite").
userread(1,"/none/nowrite/noexec").
userread(1,"/nowrite").
userspecial(0,"/").
userspecial(0,"/all").
userspecial(0,"/all/noexec").
userspecial(0,"/all/noexec/noread").
userspecial(0,"/all/noread").
userspecial(0,"/all/noread/nowrite").
userspecial(0,"/all/nowrite").
userspecial(0,"/all/nowrite/noexec").
userspecial(0,"/noexec").
userspecial(0,"/none").
userspecial(0,"/none/noexec").
userspecial(0,"/none/noexec/noread").
userspecial(0,"/none/noread").
userspecial(0,"/none/noread/nowrite").
userspecial(0,"/none/nowrite").
userspecial(0,"/none/nowrite/noexec").
userspecial(0,"/noread").
userspecial(0,"/nowrite").
userwrite(0,"/").
userwrite(0,"/all/noread/nowrite").
userwrite(0,"/all/nowrite").
userwrite(0,"/none").
userwrite(0,"/none/noread/nowrite").
userwrite(0,"/none/nowrite").
userwrite(0,"/nowrite").
userwrite(1,"/all").
userwrite(1,"/all/noexec").
userwrite(1,"/all/noexec/noread").
userwrite(1,"/all/noread").
userwrite(1,"/all/nowrite/noexec").
userwrite(1,"/noexec").
userwrite(1,"/none/noexec").
userwrite(1,"/none/noexec/noread").
userwrite(1,"/none/noread").
userwrite(1,"/none/nowrite/noexec").
userwrite(1,"/noread").
